<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net4.5;net8.0</TargetFrameworks>
    <FileVersion>1.0.0.1</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <Version>1.0.1</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <OutputType>Library</OutputType>
  </PropertyGroup>

</Project>
