using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace EasyNet.Win
{
    /// <summary>
    /// 输入数据
    /// </summary>
    [StructLayout(LayoutKind.Explicit)]
    public struct INPUT
    {
        /// <summary>
        /// Indicates the type of device information this structure carries. It is one of the following values.
        /// </summary>
        [FieldOffset(0)]
        public uint type;
        /// <summary>
        /// MOUSEINPUT structure that contains information about simulated mouse input.
        /// </summary>
        [FieldOffset(4)]
        public MOUSEINPUT mi;
        /// <summary>
        /// KEYBDINPUT structure that contains information about simulated keyboard input.
        /// </summary>
        [FieldOffset(4)]
        public KEYBDINPUT ki;
        /// <summary>
        /// HARDWAREINPUT structure that contains information about a simulated input device message.
        /// </summary>
        [FieldOffset(4)]
        public HARDWAREINPUT hi;
    }
    /// <summary>
    /// 鼠标输入
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct MOUSEINPUT
    {
        /// <summary>
        /// Provides the absolute position of the mouse, or the amount of motion since the last mouse event was generated, depending on the value of the dwFlags member. Absolute data is provided as the x coordinate of the mouse; relative data is provided as the number of pixels moved.
        /// </summary>
        public int dx;
        /// <summary>
        /// Provides the absolute position of the mouse, or the amount of motion since the last mouse event was generated, depending on the value of the dwFlags member. Absolute data is provided as the y coordinate of the mouse; relative data is provided as the number of pixels moved.
        /// </summary>
        public int dy;
        /// <summary>
        /// If dwFlags contains MOUSEEVENTF_WHEEL, then mouseData provides the amount of wheel movement. A positive value indicates that the wheel was rotated forward, away from the user; a negative value indicates that the wheel was rotated backward, toward the user. One wheel click is defined as WHEEL_DELTA, which is 120.f dwFlags does not contain MOUSEEVENTF_WHEEL then mouseData should be zero.
        /// </summary>
        public int mouseData;
        /// <summary>
        /// Set of bit flags that indicate various aspects of mouse motion and button clicks. The bits in this member can be any reasonable combination of the following values.
        /// </summary>
        public uint dwFlags;
        /// <summary>
        /// Time stamp for the event, in milliseconds. If this parameter is 0, the system will provide its own time stamp.
        /// </summary>
        public int time;
        /// <summary>
        /// Data in this member is ignored.
        /// </summary>
        public IntPtr dwExtraInfo;
    }
    /// <summary>
    /// 键盘输入
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct KEYBDINPUT
    {
        /// <summary>
        /// Provides a virtual-key code. The code must be a value in the range 1 to 254. The Winuser.h header file provides macro definitions (VK_*) for each value. If the dwFlags member specifies KEYEVENTF_UNICODE, then wVk must be 0.
        /// </summary>
        public short wVk;
        /// <summary>
        /// Provides a hardware scan code for the key. If dwFlags specifies KEYEVENTF_UNICODE, then wScan specifies a Unicode character that is to be sent to the foreground application.
        /// </summary>
        public short wScan;
        /// <summary>
        /// Provides various aspects of a keystroke. This member can be a combination of the following values.
        /// </summary>
        public int dwFlags;
        /// <summary>
        /// Data in this member is ignored.
        /// </summary>
        public int time;
        /// <summary>
        /// Data in this member is ignored.
        /// </summary>
        public IntPtr dwExtraInfo;
    }
    /// <summary>
    /// 硬件输入
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct HARDWAREINPUT
    {
        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public int uMsg;
        /// <summary>
        /// The low-order word of the lParam parameter for uMsg.
        /// </summary>
        public short wParamL;
        /// <summary>
        /// The high-order word of the lParam parameter for uMsg.
        /// </summary>
        public short wParamH;
    }
}
