<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net3.5;net4.0;net4.5;</TargetFrameworks>
    <FileVersion>1.0.0.1</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <Version>1.0.1</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\EasyNet.WinForm.Shared\EasyNet.WinForm.Shared.projitems" Label="Shared" />

  <Import Project="..\EasyNet.Extensions.Shared\EasyNet.Extensions.Shared.projitems" Label="Shared" />

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
