<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net3.5;net4.0;net4.5;netstandard2.0;net5.0;net8.0</TargetFrameworks>
    <FileVersion>1.0.0.1</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <Version>1.0.1</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
